name: Joshua

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Install fdb and dependencies
        run: |
          sudo mkdir -p /var/lib/foundationdb/data
          wget https://github.com/apple/foundationdb/releases/download/7.1.57/foundationdb-clients_7.1.57-1_amd64.deb
          wget https://github.com/apple/foundationdb/releases/download/7.1.57/foundationdb-server_7.1.57-1_amd64.deb
          echo "c5bd7c7a6ee4a3bacb9127ba53aa0d16700c987e2dbc7931c0441b8c5f1a01b6  foundationdb-clients_7.1.57-1_amd64.deb" >> checks.txt
          echo "a4ffc466f266d4b53c972b73914bf2d13cc07cbdb817c6d3d9c529cc134990ba  foundationdb-server_7.1.57-1_amd64.deb" >> checks.txt
          sha256sum -c checks.txt && sudo dpkg -i *.deb
          sudo pip3 install -r test-requirements.txt

      - name: Test
        run: |
          pytest -v
